services:
    # app:
    #   container_name: nestjs_app
    #   build: .
    #   ports:
    #     - "4000:4000"
    #     - "4040:4040"
    #   volumes:
    #     - .:/app
    #     - /app/node_modules
    #   environment:
    #     NODE_ENV: development
    #   restart: unless-stopped
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres_data:
